client_config_backend: settings
client_config:
	client_id: 711271864671-n0m4hnb4jpvjf69qs2bjg900pf7dueln.apps.googleusercontent.com
	client_secret: 4UIUiS3PY7pvlDJXJiOY3OAl 
save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
- https://www.googleapis.com/auth/drive.file
- https://www.googleapis.com/auth/drive.install
